steps:
  # --- Step 0: Get Secrets from Secret Manager ---
  # frontendビルドでのみ必要なFirebase設定をSecret Managerから取得
  - name: "gcr.io/cloud-builders/gcloud:latest"
    id: "Get Firebase Secrets"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "frontend" ]]; then
          SECRET_KEYS=(
            "FIREBASE_API_KEY"
            "FIREBASE_APP_ID"
            "FIREBASE_MESSAGING_SENDER_ID"
            "FIREBASE_PROJECT_ID"
            "FIREBASE_STORAGE_BUCKET"
            "FIREBASE_AUTH_DOMAIN"
          )
          for KEY in "$${SECRET_KEYS[@]}"; do
            VALUE=$$(gcloud secrets versions access latest --secret="$${KEY}" --project=${PROJECT_ID})
            echo "export $${KEY}=$${VALUE}" >> /workspace/firebase_env.sh
          done
        fi

  # --- Step 1: Build Frontend (Flutter Web) ---
  - name: "ghcr.io/cirruslabs/flutter:3.35.7"
    id: "Build Frontend"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "frontend" ]]; then
          echo ">>> Building Flutter web app..."
          cd app
          source /workspace/firebase_env.sh
          flutter pub get
          flutter build web --release \
            --dart-define="FIREBASE_API_KEY=$${FIREBASE_API_KEY}" \
            --dart-define="FIREBASE_APP_ID=$${FIREBASE_APP_ID}" \
            --dart-define="FIREBASE_MESSAGING_SENDER_ID=$${FIREBASE_MESSAGING_SENDER_ID}" \
            --dart-define="FIREBASE_PROJECT_ID=$${FIREBASE_PROJECT_ID}" \
            --dart-define="FIREBASE_STORAGE_BUCKET=$${FIREBASE_STORAGE_BUCKET}" \
            --dart-define="FIREBASE_AUTH_DOMAIN=$${FIREBASE_AUTH_DOMAIN}" \
            --dart-define="BACKEND_URL=${_BACKEND_URL}"
        fi

  # --- Step 2: Deploy Firebase Rules ---
  - name: "us-docker.pkg.dev/firebase-cli/us/firebase:latest"
    id: "Deploy Firebase Rules"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "rules" ]]; then
          firebase deploy --only firestore:rules,firestore:indexes,storage --project=${PROJECT_ID}
        fi

  # --- Step 3: Build Backend Image ---
  - name: "gcr.io/cloud-builders/docker:latest"
    id: "Build Backend Image"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "backend" ]]; then
          IMAGE_TAG="${_GOOGLE_CLOUD_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_BACKEND_SERVICE_NAME}:${SHORT_SHA}"
          echo ">>> Building image $${IMAGE_TAG}"
          # Build from 'agent' directory
          docker build -t "$${IMAGE_TAG}" agent
          docker push "$${IMAGE_TAG}"
        fi

  # --- Step 4: Deploy Backend to Cloud Run ---
  - name: "gcr.io/cloud-builders/gcloud:latest"
    id: "Deploy Backend to Cloud Run"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "backend" ]]; then
          IMAGE_TAG="${_GOOGLE_CLOUD_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_BACKEND_SERVICE_NAME}:${SHORT_SHA}"
          gcloud run deploy ${_BACKEND_SERVICE_NAME} \
            --image "$${IMAGE_TAG}" \
            --platform managed \
            --region ${_GOOGLE_CLOUD_LOCATION} \
            --service-account ${_BACKEND_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=${_GOOGLE_CLOUD_LOCATION},GCS_BUCKET_NAME=${PROJECT_ID}-generated-images,SESSION_TYPE=${_SESSION_TYPE},VERTEX_AI_AGENT_ENGINE_ID=${_VERTEX_AI_AGENT_ENGINE_ID},GOOGLE_GENAI_USE_VERTEXAI=true" \
            --project=${PROJECT_ID}
          
          # Allow scale to zero, Limit max instances to 1 for cost control (Demo/PoC)
          gcloud run services update ${_BACKEND_SERVICE_NAME} --region ${_GOOGLE_CLOUD_LOCATION} --min 0 --max-instances 1 --project=${PROJECT_ID}
        fi

  # --- Step 5: Deploy Frontend to Hosting ---
  - name: "us-docker.pkg.dev/firebase-cli/us/firebase:latest"
    id: "Deploy Frontend to Hosting"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "frontend" ]]; then
          firebase deploy --only hosting --project=${PROJECT_ID}
        fi

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/${PROJECT_ID}/serviceAccounts/coco-ai-bidi-cloudbuild-sa@${PROJECT_ID}.iam.gserviceaccount.com"

substitutions:
  _DEPLOY_TARGET: "all"
  _GOOGLE_CLOUD_LOCATION: "asia-northeast1"
  _BACKEND_SA_NAME: "coco-ai-bidi-backend-sa"
  _BACKEND_SERVICE_NAME: "coco-ai-bidi-streaming-backend"
  _ARTIFACT_REGISTRY_REPO: "coco-ai-bidi-streaming"
  _SESSION_TYPE: "vertexai"
  _VERTEX_AI_AGENT_ENGINE_ID: ""
  _BACKEND_URL: ""
